# This file contains all available configuration options
version: "2"

linters:
  settings:
    govet:
      disable:
        - printf

  exclusions:

    # Excluding configuration per-path, per-linter, per-text and per-source.
    rules:
      # Exclude some linters from running on tests files.
      - path: cmd/
        linters:
          - errcheck
